### ISSUE TITLE
현재 상황

### ISSUE THREAD

**Issue by 22200667** [23-oss-team-project/Reciting-program#22]
create 완료
delete 완료
update 완료
each 완료
reciting 완료
ranVerse는 버리는 걸로? - 의미가 없는 것 같아. each랑 성격이 겹치고. 원래는 무작위로 암송하는 거였는데, 현 상황에서 그걸 구현하는건 무리고, 무작위 출력으로 전향했었는데, 그건 each가  더 나으니까.
hint는 3개 기능 중 글자 수 힌트 부분에서 한글 글자 수는 strlen으로 알 수 없어. 한글 글자 수는 실용적으로 의미가 없을 뿐 아니라, 그걸 구현하기 위해서는 기존의 프로그램을 그것만 위해서 많이 바꿔야 할 것 같아서 빼는 걸로 할게
그리고 '챕터 힌트'는 프로그램을 보니 절을 출력하는 거 같은데, 해당 절은 원래 주어지는 거여서 빼도록 할게

수정할 부분 있으면 말해줘

**Comment by jay22c** [comment]
그래 그렇게하자
